name: testing action

on:
  push:
    branches:
      - main
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: jairogomz/hello-world-javascript-action-by-jairo@v1.0.0
        with:
          who-to-greet: 'Jairo'
